### ISSUE TITLE
不支持32位CPU

### ISSUE THREAD

**Issue by asemor** [rbatis/fast_pool#1]
error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
 --> ~/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/fast_pool-0.2.0/src/lib.rs:9:25
  |
9 | use std::sync::atomic::{AtomicU64, Ordering};
  |                         ^^^^^^^^^
  |                         |
  |                         no `AtomicU64` in `sync::atomic`
  |                         help: a similar name exists in the module: `AtomicU32`

**Comment by zhuxiujia** [comment]
> error[E0432]: unresolved import `std::sync::atomic::AtomicU64` --> ~/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/fast_pool-0.2.0/src/lib.rs:9:25 | 9 | use std::sync::atomic::{AtomicU64, Ordering}; | ^^^^^^^^^ | | | no `AtomicU64` in `sync::atomic` | help: a similar name exists in the module: `AtomicU32`

你应该用 类似  i686-pc-windows-msvc ，这些32位目标编译。
